export interface CanvasTemplate {
  id: string
  name: string
  description: string
  objects: any[]
}

export const templates: CanvasTemplate[] = [
  {
    id: "blank",
    name: "Blank Canvas",
    description: "Start from scratch",
    objects: [],
  },
  {
    id: "presentation",
    name: "Presentation Slide",
    description: "Title and content layout",
    objects: [
      {
        type: "rect",
        left: 50,
        top: 50,
        width: 700,
        height: 100,
        fill: "#3b82f6",
        stroke: "#1e40af",
        strokeWidth: 2,
      },
      {
        type: "i-text",
        left: 100,
        top: 80,
        text: "Presentation Title",
        fontSize: 36,
        fill: "#ffffff",
        fontFamily: "Arial",
        fontWeight: "bold",
      },
      {
        type: "rect",
        left: 50,
        top: 200,
        width: 700,
        height: 400,
        fill: "#f3f4f6",
        stroke: "#d1d5db",
        strokeWidth: 2,
      },
      {
        type: "i-text",
        left: 100,
        top: 250,
        text: "Add your content here",
        fontSize: 24,
        fill: "#1f2937",
        fontFamily: "Arial",
      },
    ],
  },
  {
    id: "diagram",
    name: "Flow Diagram",
    description: "Connected boxes for workflows",
    objects: [
      {
        type: "rect",
        left: 100,
        top: 100,
        width: 150,
        height: 100,
        fill: "#10b981",
        stroke: "#059669",
        strokeWidth: 2,
        rx: 10,
        ry: 10,
      },
      {
        type: "i-text",
        left: 140,
        top: 135,
        text: "Start",
        fontSize: 20,
        fill: "#ffffff",
        fontFamily: "Arial",
        fontWeight: "bold",
      },
      {
        type: "rect",
        left: 350,
        top: 100,
        width: 150,
        height: 100,
        fill: "#3b82f6",
        stroke: "#1e40af",
        strokeWidth: 2,
        rx: 10,
        ry: 10,
      },
      {
        type: "i-text",
        left: 380,
        top: 135,
        text: "Process",
        fontSize: 20,
        fill: "#ffffff",
        fontFamily: "Arial",
        fontWeight: "bold",
      },
      {
        type: "rect",
        left: 600,
        top: 100,
        width: 150,
        height: 100,
        fill: "#ef4444",
        stroke: "#dc2626",
        strokeWidth: 2,
        rx: 10,
        ry: 10,
      },
      {
        type: "i-text",
        left: 645,
        top: 135,
        text: "End",
        fontSize: 20,
        fill: "#ffffff",
        fontFamily: "Arial",
        fontWeight: "bold",
      },
    ],
  },
  {
    id: "wireframe",
    name: "UI Wireframe",
    description: "Basic website layout",
    objects: [
      {
        type: "rect",
        left: 50,
        top: 50,
        width: 900,
        height: 80,
        fill: "#e5e7eb",
        stroke: "#9ca3af",
        strokeWidth: 2,
      },
      {
        type: "i-text",
        left: 100,
        top: 75,
        text: "Header / Navigation",
        fontSize: 24,
        fill: "#4b5563",
        fontFamily: "Arial",
      },
      {
        type: "rect",
        left: 50,
        top: 160,
        width: 900,
        height: 300,
        fill: "#f9fafb",
        stroke: "#9ca3af",
        strokeWidth: 2,
      },
      {
        type: "i-text",
        left: 100,
        top: 290,
        text: "Main Content Area",
        fontSize: 28,
        fill: "#6b7280",
        fontFamily: "Arial",
      },
      {
        type: "rect",
        left: 50,
        top: 490,
        width: 900,
        height: 80,
        fill: "#e5e7eb",
        stroke: "#9ca3af",
        strokeWidth: 2,
      },
      {
        type: "i-text",
        left: 100,
        top: 515,
        text: "Footer",
        fontSize: 24,
        fill: "#4b5563",
        fontFamily: "Arial",
      },
    ],
  },
]
